INSERT INTO videojuegos (titulo, descripcion, imagen, precio, fecha_lanzamiento, created_at, updated_at) VALUES
('Animal Crossing', 'Crea tu propio paraíso en una isla desierta.', 'juegos/animalcrossing.jpg', 59.99, '2020-03-20', NOW(), NOW()),
('Assassins Creed Shadows', 'Aventura de sigilo en el Japón feudal.', 'juegos/assassins_creed_shadows.jpg', 69.99, '2024-11-15', NOW(), NOW()),
('Cyberpunk 2077', 'RPG de acción en la megalópolis de Night City.', 'juegos/cyberpunk.jpg', 39.99, '2020-12-10', NOW(), NOW()),
('Elden Ring', 'Álzate, Sinluz, y déjate guiar por la gracia.', 'juegos/eldenring.jpg', 59.99, '2022-02-25', NOW(), NOW()),
('F1 24', 'El videojuego oficial del Campeonato Mundial de Fórmula 1.', 'juegos/f1.jpg', 69.99, '2024-05-31', NOW(), NOW()),
('FC 24', 'La nueva era del juego de fútbol mundial.', 'juegos/fifa24.png', 29.99, '2023-09-29', NOW(), NOW()),
('Golf With Your Friends', 'Minigolf rápido y divertido para hasta 12 jugadores.', 'juegos/golftwithyourfriends.jpg', 14.99, '2020-05-19', NOW(), NOW()),
('GTA V', 'Vive las vidas de tres criminales muy diferentes.', 'juegos/gta.jpg', 29.99, '2013-09-17', NOW(), NOW()),
('Hogwarts Legacy', 'Vive lo oculto en el mundo de los magos.', 'juegos/harrypotter.jpg', 49.99, '2023-02-10', NOW(), NOW()),
('Human Fall Flat', 'Divertido juego de plataformas basado en física.', 'juegos/humanfall.jpg', 19.99, '2016-07-22', NOW(), NOW()),
('The Sims 4: Life & Death', 'Explora el lado más oscuro y espiritual de los Sims.', 'juegos/lifeAndDeathSims4.jpg', 39.99, '2024-10-31', NOW(), NOW()),
('Overcooked! 2', 'Vuelve al Reino de la Cebolla en un caos cooperativo.', 'juegos/overcooked.jpg', 24.99, '2018-08-07', NOW(), NOW()),
('Planet Coaster 2', 'Crea el parque de atracciones de tus sueños.', 'juegos/planetCoaster2DeluxeEdition.png', 44.99, '2024-11-06', NOW(), NOW()),
('Prison Architect 2', 'Diseña y gestiona tu propio centro penitenciario.', 'juegos/prisionArchitect2.jpg', 39.99, '2024-09-03', NOW(), NOW()),
('Rainbow Six Siege', 'Shooter táctico basado en equipos.', 'juegos/raimbowsix.jpg', 19.99, '2015-12-01', NOW(), NOW()),
('The Sims 4: Cottage Living', 'Disfruta de la vida en el campo y los animales.', 'juegos/sims4cottageliving.jpg', 39.99, '2021-07-22', NOW(), NOW()),
('Spider-Man Remastered', 'La historia de Peter Parker en un Nueva York vibrante.', 'juegos/spiderman.jpg', 49.99, '2022-08-12', NOW(), NOW()),
('The Sims 4: Lovestruck', 'Encuentra el amor verdadero para tus Sims.', 'juegos/the_sims_4_lovestruck.jpg', 39.99, '2024-07-25', NOW(), NOW());