INSERT INTO "videojuegos" ("id", "titulo", "descripcion", "imagen", "precio", "seccion", "es_destacado", "created_at", "updated_at") VALUES 
('1', 'Animal Crossing', 'Crea tu propio paraíso en una isla desierta.', 'juegos/animalcrossing.jpg', 59.99, 'promociones', 'false', now(), now()), 
('2', 'Assassins Creed Shadows', 'Aventura de sigilo en el Japón feudal.', 'juegos/assassins_creed_shadows.jpg', 69.99, 'proximamente', 'false', now(), now()), 
('3', 'Cyberpunk 2077', 'RPG de acción en la megalópolis de Night City.', 'juegos/cyberpunk.jpg', 39.99, 'promociones', 'false', now(), now()), 
('4', 'Elden Ring', 'Álzate, Sinluz, y déjate guiar por la gracia.', 'juegos/eldenring.jpg', 59.99, 'novedades', 'false', now(), now()), 
('5', 'F1 24', 'El videojuego oficial del Campeonato Mundial de Fórmula 1.', 'juegos/f1.jpg', 69.99, 'novedades', 'false', now(), now()), 
('6', 'FC 24', 'La nueva era del juego de fútbol mundial.', 'juegos/fifa24.png', 29.99, 'novedades', 'false', now(), now()), 
('7', 'Golf With Your Friends', 'Minigolf rápido y divertido para hasta 12 jugadores.', 'juegos/golftwithyourfriends.jpg', 14.99, 'catalogo', 'false', now(), now()), 
('8', 'GTA V', 'Vive las vidas de tres criminales muy diferentes.', 'juegos/gta.jpg', 29.99, 'catalogo', 'false', now(), now()), 
('9', 'Hogwarts Legacy', 'Vive lo oculto en el mundo de los magos.', 'juegos/harrypotter.jpg', 49.99, 'catalogo', 'false', now(), now()), 
('10', 'Human Fall Flat', 'Divertido juego de plataformas basado en física.', 'juegos/humanfall.jpg', 19.99, 'catalogo', 'false', now(), now()), 
('11', 'The Sims 4: Life & Death', 'Explora el lado más oscuro y espiritual de los Sims.', 'juegos/lifeAndDeathSims4.jpg', 39.99, 'proximamente', 'false', now(), now()), 
('12', 'Overcooked! 2', 'Vuelve al Reino de la Cebolla en un caos cooperativo.', 'juegos/overcooked.jpg', 24.99, 'catalogo', 'false', now(), now()), 
('13', 'Planet Coaster 2', 'Crea el parque de atracciones de tus sueños.', 'juegos/planetCoaster2DeluxeEdition.png', 44.99, 'proximamente', 'false', now(), now()), 
('14', 'Prison Architect 2', 'Diseña y gestiona tu propio centro penitenciario.', 'juegos/prisionArchitect2.jpg', 39.99, 'proximamente', 'false', now(), now()), 
('15', 'Rainbow Six Siege', 'Shooter táctico basado en equipos.', 'juegos/raimbowsix.jpg', 19.99, 'catalogo', 'false', now(), now()), 
('16', 'The Sims 4: Cottage Living', 'Disfruta de la vida en el campo y los animales.', 'juegos/sims4cottageliving.jpg', 39.99, 'promociones', 'false', now(), now()), 
('17', 'Spider-Man Remastered', 'La historia de Peter Parker en un Nueva York vibrante.', 'juegos/spiderman.jpg', 49.99, 'catalogo', 'false', now(), now()), 
('18', 'The Sims 4: Lovestruck', 'Encuentra el amor verdadero para tus Sims.', 'juegos/the_sims_4_lovestruck.jpg', 39.99, 'catalogo', 'false', now(), now());